### ISSUE TITLE
As a player, after seeing the generated image, I want to guess the input prompt within the pre-set time limit, so that I can score points based on my accuracy, enhancing the game's interactivity and engagement.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-client#31]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#34
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#33
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#2
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#32
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#30

**Comment by eduard54** [comment]
commit: 0ce79ac

**Comment by eduard54** [comment]
commit: 391b969
