### ISSUE TITLE
As a game host, I want to specify other optional game settings, so that I can customize the game experience for all participants.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-client#37]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#36
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#51
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#35
