### ISSUE TITLE
As a user, I want to leave the lobby by clicking on a home button when the game is over, so that i can join or create a new game.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-client#61]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#62
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#107
- [x] sopra-fs24-group-32/sopra-fs24-group-32-server#108
