### ISSUE TITLE
As a player, when it's my turn, I want to provide a text description based as input to DALL-E, so that an image for the round gets created.

### ISSUE THREAD

**Issue by nicolasHuber3** [sopra-fs24-group-32/sopra-fs24-group-32-client#7]
**Acceptance Criteria:**
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#12
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#16
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#15
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#14
- [x] sopra-fs24-group-32/sopra-fs24-group-32-client#13

**Comment by eduard54** [comment]
commit: 0ce79ac
